# 3장 파이썬을 이용한 데이터 분석

## 3.1 파이썬을 이용한 기술통계: 1변량 데이터

### 통계처리와 scipy

In [1]:
# 데이터를 저장하기 위한 numpy, 통계량 기산 등 기본적 데이터 분석에 사용되는 scipy를 불러옴
import numpy as np
import scipy as sp

# 자릿수 지정
%precision 3

'%.3f'

### 1변량 데이터의 관리

In [2]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

### 합계와 샘플사이즈

In [3]:
np.sum(fish_data)

40

In [4]:
fish_data.sum()

40

In [5]:
sum(fish_data)

40

In [6]:
# 샘플사이즈
len(fish_data)

10

### 평균값(기댓값)

In [7]:
# 평균 계산
N = len(fish_data)
sum_value = np.sum(fish_data)
mu = sum_value / N
mu

4.0

In [11]:
# 함수를 사용한 평균 값 계산
np.mean(fish_data)
fish_data.mean()

4.0

### 표본분산

In [12]:
sigma_2_sample = np.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.2

In [13]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [14]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [15]:
(fish_data - mu) ** 2

array([4., 1., 1., 0., 0., 0., 0., 1., 1., 4.])

In [16]:
np.sum((fish_data - mu) ** 2)

12.0

In [17]:
# 함수를 사용한 표본 분산
np.var(fish_data, ddof = 0)

1.2

### 불편분산

In [18]:
# 불편분산 = 편향이 없다
sigma_2 = np.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

1.3333333333333333

In [21]:
# 불편분산 
np.var(fish_data, ddof = 1) 
#np.var(fish_data) #표본분산

1.3333333333333333

### 표준편차

In [24]:
#불편분산의 표준편차
sigma = np.sqrt(sigma_2)
sigma

1.1547005383792515

In [25]:
# 함수 사용
np.std(fish_data, ddof = 1)

1.1547005383792515

### 표준화

Z = (X-평균)/표준편차

In [33]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [34]:
np.mean(fish_data - mu)

0.0

In [35]:
fish_data / sigma

array([1.732, 2.598, 2.598, 3.464, 3.464, 3.464, 3.464, 4.33 , 4.33 ,
       5.196])

In [36]:
np.std(fish_data / sigma, ddof = 1)

1.0

In [30]:
standard = (fish_data - mu) / sigma #표준화 하는 과정
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [37]:
np.mean(standard)

2.2204460492503132e-17

In [38]:
np.std(standard, ddof = 1)

1.0

### 그 외의 통계량

In [39]:
# 최댓값
np.amax(fish_data)

6

In [40]:
# 최솟값
np.amin(fish_data)

2

In [46]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [45]:
# 중앙값
np.median(fish_data)
    

4.0

In [42]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [43]:
np.mean(fish_data_2)

13.4

In [44]:
np.median(fish_data_2) #중간값은 그대로

4.0

### scipy.stats와 사분위수

In [47]:
from scipy import stats

In [48]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)

3.0

In [49]:
stats.scoreatpercentile(fish_data_3, 75)

7.0

In [51]:
stats.scoreatpercentile(fish_data_3, 99) #99% 위치한 값 반환

8.92